package com.example.aather.service

enum class ComunicationServiceActions {
    START_SERVICE,SETUP_VIEWS,END_CALL,SWITCH_CAMERA,TOGGLE_AUDIO,TOGGLE_VIDEO,TOGGLE_AUDIO_DEVICE,
    TOGGLE_SCREEN_SHARE,STOP_SERVICE
}